services:
  # Backend service (Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-converter-backend
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - backend_uploads:/app/uploads
      - backend_converted:/app/converted
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Frontend service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdf-converter-frontend
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Caddy reverse proxy
  caddy:
    image: caddy:2.7.6-alpine
    container_name: pdf-converter-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  backend_uploads:
    driver: local
  backend_converted:
    driver: local

networks:
  app-network:
    driver: bridge
